### ISSUE TITLE
Python 3.10

### ISSUE THREAD

**Issue by jccaleroe** [delta-io/delta-sharing#110]
I can't install on Python 3.10, it seems this version of Python only fixed a bug, so I do not see the problem of restricting to version < 3.10.
I changed the restriction and install it on Python 3.10 and all worked perfectly splendid

**Comment by zsxwing** [comment]
Good catch. Feel free to submit a PR to remove the restriction.

**Comment by zsxwing** [comment]
Fixed by #111
