### ISSUE TITLE
Not able to access GCS delta data using Python 3.6

### ISSUE THREAD

**Issue by BShraman** [delta-io/delta-sharing#115]
**Error** : I am not able to access GCS delta data with Python 3.6 version with below message. 
<img width="468" alt="image" src="https://user-images.githubusercontent.com/49772843/155591436-0f7d37e1-fc2e-4343-b5dd-70d7510e6327.png">

I am able to access parquet file printed in error message. 

**Solution**: This issue has been resolved using python3.8

**Slack Thread** 
https://delta-users.slack.com/archives/C023H5LS51P/p1645650761171099?thread_ts=1645650761.171099&cid=C023H5LS51P](https://urldefense.proofpoint.com/v2/url?u=https-3A__delta-2Dusers.slack.com_archives_C023H5LS51P_p1645650761171099-3Fthread-5Fts-3D1645650761.171099-26cid-3DC023H5LS51P&d=DwMFaQ&c=1hIq-C3ayh4zm6RZ7m4R2AxLax342Ba687_wO3ZmnvQ&r=BEU_jKcCgZCKXfyreR9nxUI6GR4XQvaAfWli5I_Owg4&m=O-HHCNT-RW4GxGhotR3_aZartO2vhdg2D_Om5mxXxl_d_9GQcOj9ghW2o7E-3tkL&s=w0od_Ql-k-9eeYpdfsY79h744TcoA4XxeN8M8c79dr4&e=)

**Comment by zsxwing** [comment]
Thanks for reporting the issue. I hit a different error when trying Python 3.6: #116 . Looks like fsspec doesn't work with Python 3.6. We will change the Python version requirement to >= 3.7.

**Comment by zsxwing** [comment]
Closing this as per #116.
