### ISSUE TITLE
Filtering does not work

### ISSUE THREAD

**Issue by ckayay** [delta-io/delta-sharing#123]
Hi,
The filtering does work as suggested here. It brings all the records...
https://github.com/delta-io/delta-sharing/blob/main/PROTOCOL.md#read-data-from-a-table

I am trying the following:
curl -X POST [...../delta-sharing/shares/covidshare/schemas/conformed/tables/fact_covid/query](http://...../delta-sharing/shares/covidshare/schemas/conformed/tables/fact_covid/query) -H “Accept: application/json” -H “Content-Type: application/json” -d ’{“predicateHints”: [“date_sk >= ‘2021-01-01’“,”date_sk <= ‘2021-01-02’“], “limitHint”: 1}'

OR
curl -X POST [...../delta-sharing/shares/covidshare/schemas/conformed/tables/fact_covid/query](http://...../delta-sharing/shares/covidshare/schemas/conformed/tables/fact_covid/query) -H “Accept: application/json” -H “Content-Type: application/json” -d ’{“predicateHints”: [“date >= ‘2021-01-01’“,”date <= ‘2021-01-02’“], “limitHint”: 1}'

OR
curl -X POST [...../delta-sharing/shares/covidshare/schemas/conformed/tables/fact_covid/query](http://...../delta-sharing/shares/covidshare/schemas/conformed/tables/fact_covid/query) -H “Accept: application/json” -H “Content-Type: application/json” -d ‘{“limitHint”: 1}’

OR
curl -X POST http://deltasharing-dev.westeurope.azurecontainer.io:8181/delta-sharing/shares/covidshare/schemas/conformed/tables/fact_covid/query -H "Accept: application/json" -H "Content-Type: application/json" -d '{"predicateHints": ["date_sk >= 2021-01-01","date_sk <= 2021-01-02"], "limitHint": 1}'

OR
curl -X POST http://deltasharing-dev.westeurope.azurecontainer.io:8181/delta-sharing/shares/covidshare/schemas/conformed/tables/fact_covid/query -H "Accept: application/json" -H "Content-Type: application/json" -d '{"predicateHints": ["date >= 2021-01-01","date <= 2021-01-02"], "limitHint": 1}'

**Comment by zsxwing** [comment]
We turned off the `predicateHints` support in our open server. This is the config: https://github.com/delta-io/delta-sharing/blob/b70e1ae23bdca58a97a8ab4b0e272d702ee7c2ce/server/src/universal/conf/delta-sharing-server.yaml.template#L44

`limitHint` will require file stats which OSS Delta Lake is going to release in https://github.com/delta-io/delta/pull/924

Currently both of them are optional, and the server will use them as hints rather than an enforcement. The client will still need to apply the filters and limit by itself.

**Comment by ckayay** [comment]
thanks for the hint!

**Comment by zsxwing** [comment]
Closing this as it's answered

**Comment by ckayay** [comment]
One issue is that, the filtering still not working. One has to bring all the records and then do the filtering in memory.

**Comment by ckayay** [comment]
Not sure why but, the filtering still does not work. It still brings all the records. Anything else to make sure that the filtering might work?

{"predicateHints": ["date_sk >= '2021-01-01'"],"limitHint": 1000}
{"predicateHints": ["date >= '2021-01-01'"],"limitHint": 1000}

![image](https://user-images.githubusercontent.com/12582721/158567215-bdef9081-849c-4e3f-9895-37544f517f15.png)
