### ISSUE TITLE
Delta Sharing API for easy cloning as Delta

### ISSUE THREAD

**Issue by stephanieamrivera** [delta-io/delta-sharing#143]
We would like to use Delta Sharing from one Region and Metastore to another as a type of replication between primary and secondary sites without sharing S3 buckets or doing cross-mounted buckets.

**Comment by Basem-Gaber** [comment]
I believe this is a good use-case.

It could be handled by exposing the difference between a table's version and another.

This difference can then be replicated at the secondary site to eventually become an effective clone of the primary site.

My idea here is inspired by the new "changes" API in here https://github.com/delta-io/delta-sharing/pull/135

**Comment by zsxwing** [comment]
Delta Lake is going to add table cloning in Q3 ( https://github.com/delta-io/delta/issues/920 ). It's probably a better solution than doing it in the Delta Sharing project. Feel free to post your comment in the ticket to help us evaluate the feature priority 😄

**Comment by linzhou-db** [comment]
Closing the issue given the last answer was endorsed by the original requester, feel free to reopen.
