### ISSUE TITLE
Delta lakes in Azure containers configured with SoftDelete is not supported

### ISSUE THREAD

**Issue by ckayay** [delta-io/delta-sharing#156]
For delta lake tables stored in azure blob configured with "Soft Delete" enabled, the delta sharing server is giving error as shown below. We need this setting enabled for the table to be refreshed daily (removed, created from scratch or owerwritten, etc) and delta lake operations fail when Soft Delete is disabled. So, it is chicken-egg problem at the moment for us. Why delta sharing needs Azure Storage accounts with Soft Delete is disabled?

Caused by: Operation failed: “This endpoint does not support BlobStorageEvents or SoftDelete. Please disable these account features if you would like to use this endpoint.”

**Comment by zsxwing** [comment]
Based on https://docs.microsoft.com/en-us/answers/questions/845340/delete-activity-in-adf-failing-to-delete-a-the-fil.html , this seems you are not using the right storage type. If you are using [Azure Blog Storage](https://github.com/delta-io/delta-sharing#azure-blob-storage), could you try to switch to [Azure Data Lake Storage Gen2](https://github.com/delta-io/delta-sharing#azure-data-lake-storage-gen2) ? Vice versa.

**Comment by zsxwing** [comment]
Closing the stale ticket. Feel free to re-open if there is any update
