### ISSUE TITLE
 ValueError: read of closed file (using file path that has been working in the previous month) 

### ISSUE THREAD

**Issue by serra98** [delta-io/delta-sharing#182]
Hi delta-sharing community, 
I wanted to know if anyone else is seeing the same issue. 
I'm getting this error running ` client = delta_sharing.SharingClient(file_path)`  using the file path that has been working fine past few months.  (no changes in file or file path) 

`ValueError : read of closed file` 

my file is stored in /dbfs/FileStore/shared_uploads/ using databricks. 
file inside format is following the original guideline: 
{
  "shareCredentialsVersion": 1,
  "endpoint": "delta-sharing-path",
  "bearerToken": ""
}

Detailed Error lines: 

`----> 1 client = delta_sharing.SharingClient(file_path)

/databricks/python/lib/python3.8/site-packages/delta_sharing/delta_sharing.py in __init__(self, profile)
    188     def __init__(self, profile: Union[str, BinaryIO, TextIO, Path, DeltaSharingProfile]):
    189         if not isinstance(profile, DeltaSharingProfile):
--> 190             profile = DeltaSharingProfile.read_from_file(profile)
    191         self._profile = profile
    192         self._rest_client = DataSharingRestClient(profile)

/databricks/python/lib/python3.8/site-packages/delta_sharing/protocol.py in read_from_file(profile)
     49             infile = profile
     50         try:
---> 51             return DeltaSharingProfile.from_json(infile.read())
     52         finally:
     53             infile.close()

/databricks/python/lib/python3.8/site-packages/fsspec/implementations/local.py in read(self, *args, **kwargs)`

**Comment by zsxwing** [comment]
Could you double check if the profile file is broken or not? This looks like a DBFS issue rather than an issue in Delta Sharing. Could you try to talk to your Databricks support if the issue still happens?

**Comment by serra98** [comment]
closing this issue
- I have just figured out that this was due to new delta-sharing-server 0.5.0  version. upgraded -> no issue
