### ISSUE TITLE
Create recipient link for Tableau Web Connector

### ISSUE THREAD

**Issue by skaplan81** [delta-io/delta-sharing#183]
Hi Delta Sharing Community

I want to share the activation link for my local delta sharing server using python so that I could use web connector of Tableau and open my delta tables in Tableau, is it possible?

I watched this video and want to the the exact same at the 22:50

https://www.youtube.com/watch?v=HQRusxdkwFo

Thanks in advance

**Comment by skaplan81** [comment]
Hi all, I cannot get any response, could you please help with this issue?

**Comment by linzhou-db** [comment]
@skaplan81 Hi, sorry for the late response. We'll be catching up on the issues in this repo, and will have a more prompt response later.

For you request, I think it's possible. you don't need an activation link, you only need to set the bearertoken for the recipient, and send it to the recipient.

**Comment by linzhou-db** [comment]
@skaplan81 Closing this for now, feel free to reopen is you find the solution not working for you.
