### ISSUE TITLE
Incompatible versions of aws-java-sdk-bundle: the bundled one and the one expected by hadoop-aws

### ISSUE THREAD

**Issue by ThachNgocTran** [delta-io/delta-sharing#191]
I'm using Delta Sharing 0.5.1. Checking its `lib` folder, I found those JARs:

```
com.amazonaws.aws-java-sdk-bundle-1.12.189.jar
...
org.apache.hadoop.hadoop-aws-2.10.1.jar
```

According to this [Maven Repo](https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-aws/2.10.1), this version `2.10.1` of "**Apache Hadoop Amazon Web Services Support**" requires "**aws-java-sdk-bundle**" `1.11.271` (released on Jan 27, 2018). However, in the list of JARs above, we can see the version `1.12.189` (released on Mar 30, 2022) was included. 4+ years difference!

I'm not professional on Java, but I think this incompatibility can cause problems further down the line.

**Comment by zsxwing** [comment]
We have S3 integration tests to make sure we don't touch any incompatible code path. It's working and we haven't seen any incompatible issues. Hence I'm closing this one. Feel free to reopen this one if you hit any real incompatible issues.
