### ISSUE TITLE
Support Google Cloud Storage in Delta Sharing Server

### ISSUE THREAD

**Issue by zsxwing** [delta-io/delta-sharing#20]
Google Cloud Storage supports [Signed URLs](https://cloud.google.com/storage/docs/access-control/signed-urls). It's not hard to make Delta Sharing Server support it.

**Comment by kohei-tosshy** [comment]
Hello.
I am trying to implement this by using GCP-connector for Hadoop 2.
Hadoop 2 API is also used for S3 and Azure in Delta Sharing.
But, there is a depencency problem between Spark and GCP-connector for Hadoop 2 related with Google Guava.
(https://cloud.google.com/dataproc/docs/guides/manage-spark-dependencies)

I think we can choose two way to solve this problem.

1. Use GCP-connector for Hadoop 2, then solve the depencency problem by sbt's shading 
2. Use GCP-connector for Hadoop 3. This cause the Hadoop API's difference among the cloud storages, but we don't need to use shading bacause no dependency problem occurs.

I want to ask which way is better.

**Comment by zsxwing** [comment]
Can we exclude guava in build.sbt? I remember we don't use it. If it's not working, I prefer option 2. We can just upgrade Hadoop version to 3 in the server project.

**Comment by zsxwing** [comment]
@kohei-tosshy Feel free to reach us if you hit any issue. I will try to get a GCS account in parallel so that we can set up integration tests when you have a PR ready.

**Comment by zsxwing** [comment]
This is added by #81 81
