### ISSUE TITLE
Support Azure Storage in Delta Sharing Server

### ISSUE THREAD

**Issue by zsxwing** [delta-io/delta-sharing#21]
Azure supports [shared access signature](https://docs.microsoft.com/en-us/rest/api/storageservices/delegate-access-with-shared-access-signature) which is similar to signed url in other storage systems. It's not hard to make Delta Sharing Server support it.

**Comment by jesseryoungVUMC** [comment]
For support of Azure Storage, please consider using the Azure SDK's `DefaultAzureCredentials` (https://docs.microsoft.com/en-us/java/api/com.azure.identity.defaultazurecredential?view=azure-java-stable). 

This will allow the use of Azure Managed Identity when accessing ADLS Gen2 via Azure Functions or Virtual Machines as well as supporting the standard Azure authentication environment variables.

**Comment by zsxwing** [comment]
> For support of Azure Storage, please consider using the Azure SDK's `DefaultAzureCredentials` (https://docs.microsoft.com/en-us/java/api/com.azure.identity.defaultazurecredential?view=azure-java-stable).

@jesseryoungVUMC Thanks for the pointers. However, `DefaultAzureCredentials` is not supported by [hadoop-azure](https://hadoop.apache.org/docs/stable/hadoop-azure/index.html). As we need to use hadoop-azure to read the data on Azure storages, we just follow the same way to configure credentials as hadoop-azure. See #59 for more details.

**Comment by jesseryoungVUMC** [comment]
> > For support of Azure Storage, please consider using the Azure SDK's `DefaultAzureCredentials` (https://docs.microsoft.com/en-us/java/api/com.azure.identity.defaultazurecredential?view=azure-java-stable).
> 
> @jesseryoungVUMC Thanks for the pointers. However, `DefaultAzureCredentials` is not supported by [hadoop-azure](https://hadoop.apache.org/docs/stable/hadoop-azure/index.html). As we need to use hadoop-azure to read the data on Azure storages, we just follow the same way to configure credentials as hadoop-azure. See #59 for more details.

It looks like you could possibly create a [custom oauth token provider](https://hadoop.apache.org/docs/stable/hadoop-azure/abfs.html#Custom_OAuth_2.0_Token_Provider) that could use the azure identity library's `DefaultAzureCredential` to return a token. That may be outside of the scope of this project, and is pretty trivial to implement if somebody wanted to. 

Regardless, with hadoop-azure now in the project, I think we can easily configure [Managed Identity](https://hadoop.apache.org/docs/stable/hadoop-azure/abfs.html#Azure_Managed_Identity) as well as setting an OAuth token and refresh token explicitly.

**Comment by zsxwing** [comment]
@jesseryoungVUMC Thanks! Do you know whether we can use the OAuth token to generate shared access signature (SAS, Azure's pre signed url)?

**Comment by jesseryoungVUMC** [comment]
I believe you can create a user delegation SAS using the OAuth token: https://docs.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas. I'm searching around to see if I can find an example where you can do it with the azure libraries instead of interacting directly with the REST api.
