### ISSUE TITLE
Clarification regarding predicate pushdown

### ISSUE THREAD

**Issue by chitralverma** [delta-io/delta-sharing#242]
Does this library take into account the `stats` field present in the transaction log of a particular table version to filter the parquet files that are supposed to be read while instantiating a `DeltaTable`?

For example, I have a table with total 100 records across 2 table versions and each version has 5 parquet files associated with it covering 50 records of that version (assuming even 10 records per parquet file). The transaction log for both versions contains a `stats` field with information like `minValues`, `maxValues`, `nullCount` etc. 

I have already verified that if I try to read first version (0), the `DeltaTable` object will read only 1 files and for second version (1) it will read both the files. This means that the number of parquet files are affected by the version already.

Just needed a clarification whether the `stats` fields are also used anywhere for selection of files to be read?

**Comment by zsxwing** [comment]
Data skipping using stats in Delta Sharing is not supported yet.

**Comment by CrawX** [comment]
@zsxwing can you make any statement where this is on the roadmap? Having data skipping in spark could be super useful for performance... I can also open another issue if thats preferred.
