### ISSUE TITLE
Question about compatibility with other open table formats

### ISSUE THREAD

**Issue by N4ims** [delta-io/delta-sharing#250]
Hi fellow devs, I wonder if the protocol is also compatible with the use of other open table formats like Apache Iceberg or Apache Hudi.
I am unsure because I have not found anything on this yet.

**Comment by zsxwing** [comment]
It doesn't support other open table formats like Apache Iceberg or Apache Hudi right now. But the protocol is designed to be open. If you are interested and have time, you are welcome to explore the protocol and provide feedback or even pull requests on what would need to be done to support other formats.

**Comment by N4ims** [comment]
Thank you for the answer =). Due to my lack of time, I unfortunately can't participate right now. But maybe I'll find the time in the future.
