### ISSUE TITLE
delta sharing server gives 405 Method Not Allowed while using query REST API endpoint

### ISSUE THREAD

**Issue by sristiraj** [delta-io/delta-sharing#254]
Hi,

I am trying to run delta sharing sample server on my machine and using query endpoint to query data. However, invoking the endpoint gives 405 Method Not Allowed while other endpoints are working as expected.

Could you please help with setting to be used to make this endpoint work?

Below is delta-sharing-server-config.yaml content.

version: 1
shares:
- name: "share1"
  schemas:
  - name: "schema1"
    tables:
    - name: "table1"
      location: "s3a://sr-databricks/delta"
host: "localhost"
port: 8081
endpoint: "/delta-sharing"
preSignedUrlTimeoutSeconds: 3600
deltaTableCacheSize: 10
stalenessAcceptable: false
evaluatePredicateHints: true

**Endpoint query:** http://127.0.0.1:8081/delta-sharing/shares/share1/schemas/schema1/tables/table1/query

**Headers:** 

Content-Type: application/json
Accept-Charset: utf-8

**Request Body:** 
{
  "version": 0
}

**Comment by zsxwing** [comment]
How do you send the request? This endpoint `http://127.0.0.1:8081/delta-sharing/shares/share1/schemas/schema1/tables/table1/query` needs to use HTTP POST.

**Comment by sristiraj** [comment]
Thanks! That was a silly miss. I will close this issue as this is working expected.
