### ISSUE TITLE
The query endpoint should return a 400 on invalid input

### ISSUE THREAD

**Issue by rtyler** [delta-io/delta-sharing#27]
Let's just say, hypothetically speaking some idiot were to pass the wrong type of JSON object for `predicateHints`, the API will 500.

```
curl -X POST "https://sharing.delta.io/delta-sharing/shares/delta_sharing/schemas/default/tables/COVID_19_NYT/query" -H  "accept: application/x-ndjson" -H  "Authorization: Bearer faaie590d541265bcab1f2de9813274bf233" -H  "Content-Type: a
pplication/json" -d "{\"predicateHints\":{},\"limitHint\":1000}"
```

Since I'm the idiot, I should be given a 400 error which means that the request was incorrectly formed.

**Comment by mateiz** [comment]
Good catch, we'll look into this.

**Comment by zsxwing** [comment]
@rtyler Good catch. This will be fixed by #32.

**Comment by zsxwing** [comment]
@rtyler Thanks for reporting this. The fix has been merged. The server is also updated with the latest change that should report the 400 error for an invalid json.

**Comment by rtyler** [comment]
@zsxwing did y'all happen to set up a CD pipeline for the demo site, or will we need to wait for Denny to get back from his "Eat. Throw. Love." ultimate frisbee vacation? :smile:

**Comment by zsxwing** [comment]
We have not set up an automatic CD pipeline yet. I'm doing the deployment manually. But this is a good idea. I will wait for Denny and get his help 😄 .
