### ISSUE TITLE
DataSharingRestClient not included for python yet?

### ISSUE THREAD

**Issue by Gcdelgado150** [delta-io/delta-sharing#289]
Hi! 
I've checked the last update based on this issue ( [https://github.com/delta-io/delta-sharing/pull/111](url) ) and some documentation saying that with DataSharingRestClient is possible to use query_table_version().

After some dig around I was able to include everything needed in my __init__.py file and able to use the method in my package installed.

I was wondering why that was not included in commited code yet? Is the version for python not stable yet?

Thank you!

Btw, in my case worked like a charm:

"QueryTableVersionResponse(delta_table_version=7)"

**Comment by linzhou-db** [comment]
@Gcdelgado150 What exactly is not included? 
query_table_version is available in the rest_client.py, do you mean to expose it in `readers.py` and `delta_sharing.py`?

**Comment by Gcdelgado150** [comment]
Is not included "all" in __init__.py file, therefore not accessible when you would import the package  Or not? Am I missing something? hehe

**Comment by linzhou-db** [comment]
You meant this file right: https://github.com/delta-io/delta-sharing/blob/main/python/delta_sharing/__init__.py
Yeah, once it's exposed in delta_sharing, it will be exposed there. 

Feel free to send out a PR to expose it.

**Comment by Gcdelgado150** [comment]
Based on your questioning I actually figure it that the exposure was indeed there, but not straight, meaning that: "from delta_sharing import DataSharingRestClient" wouldn't work. But instead "from delta_sharing.delta_sharing import DataSharingRestClient" is correct. 

Is that work for a PR, or not even needed? Was that intentional? Sorry, noobs question I guess! You can close the issue! 
Ty

**Comment by linzhou-db** [comment]
I think it's more about with limited bandwidth, we prioritize the ones used by most people. As there are always work around, so we didn't prioritize this. 
Thanks, I'll close the issue for now, feel free to reopen or send out PRs.
