### ISSUE TITLE
 fs.s3.awsAccessKeyId and fs.s3.awsSecretAccessKey properties must be present

### ISSUE THREAD

**Issue by Aayushpatel007** [delta-io/delta-sharing#29]
![Screenshot from 2021-05-28 13-42-45](https://user-images.githubusercontent.com/33193189/120026349-f0877500-bfbf-11eb-8c73-f5af93d31af1.png)

Even after having IAM role access to S3 and specifying AWS_ACCESS_KEY and AWS_SECRET_ACCESS_KEY. I am having this error in server logs. 
As it uses hadoop-aws to read files, how do we authenticate and pass credentials in server? 

Before running the below command, where should I specify fs.s3.awsAccessKeyId and fs.s3.awsSecretAccessKey properties? 
 bin/delta-sharing-server -- --config conf/delta-sharing-server.yaml

**Comment by skaplan81** [comment]
getting the same error, did you solve your problem? Where should I place these keys, in the .yaml file or .share file?

**Comment by zsxwing** [comment]
> getting the same error, did you solve your problem? Where should I place these keys, in the .yaml file or .share file?

@skaplan81 could you try to use the `s3a://` path?

**Comment by gauravbrills** [comment]
I think it worked for me finally remember adding hadoop core-site.xml with aws config to get it running on a container .Just on docker the path was diff /opt/docker/conf which @zsxwing  helped me point at

**Comment by skaplan81** [comment]
> > getting the same error, did you solve your problem? Where should I place these keys, in the .yaml file or .share file?
> 
> @skaplan81 could you try to use the `s3a://` path?

I am copying the address from S3 page and it starts 's3://', but everywhere I see links starting with s3a, doesn't understand

**Comment by skaplan81** [comment]
I have yaml file as below : 

version: 1
shares:
- name: "share1"
  schemas:
  - name: "schema1"
    tables:
    - name: "table1"
      location: "s3a://sharingcentertrial1/deneme"
host: "localhost"
port: 8080
endpoint: "/delta-sharing"
preSignedUrlTimeoutSeconds: 3600
deltaTableCacheSize: 10
stalenessAcceptable: false
evaluatePredicateHints: false

share file as this : 

{
  "shareCredentialsVersion": 1,
  "endpoint": "http://localhost:8080/delta-sharing",
  "bearerToken": ""
}

I created IAM user with a role and privacy settings. But I don't know where should I place these lines?

export AWS_ACCESS_KEY_ID=my.aws.key
export AWS_SECRET_ACCESS_KEY=my.secret.key

thanks for all in advance

**Comment by zsxwing** [comment]
Can you run the following commands?
```
export AWS_ACCESS_KEY_ID=my.aws.key
export AWS_SECRET_ACCESS_KEY=my.secret.key
bin/delta-sharing-server -- --config conf/delta-sharing-server.yaml
```

**Comment by zsxwing** [comment]
> I am copying the address from S3 page and it starts 's3://', but everywhere I see links starting with s3a, doesn't understand

`s3://` paths usually are mapped to EMR's own S3 file system implementation (Delta Sharing cannot use it since it's not open sourced), and `s3a://` paths are mapped to open source Hadoop S3AFileSystem which is the one used by Delta Sharing.

**Comment by skaplan81** [comment]
> Can you run the following commands?
> 
> ```
> export AWS_ACCESS_KEY_ID=my.aws.key
> export AWS_SECRET_ACCESS_KEY=my.secret.key
> bin/delta-sharing-server -- --config conf/delta-sharing-server.yaml
> ```

tried this but got the same error

**Comment by zsxwing** [comment]
@skaplan81 Is the exception thrown from `S3FileSystem` or `S3*A*FileSystem`?

**Comment by skaplan81** [comment]
> @skaplan81 Is the exception thrown from `S3FileSystem` or `S3*A*FileSystem`?

I am using S3 URI in the yaml file, is it what are you asking?

**Comment by skaplan81** [comment]
I am trying to follow the steps mentioned in this link, but I think skipping some steps

https://github.com/delta-io/delta-sharing#s3

**Comment by zsxwing** [comment]
> I am using S3 URI in the yaml file, is it what are you asking?

Yep. Please use `s3a://`. Will highlight this in the doc as this is not obvious for people not familiar with multiple S3 file systems story.

**Comment by skaplan81** [comment]
> > I am using S3 URI in the yaml file, is it what are you asking?
> 
> Yep. Please use `s3a://`. Will highlight this in the doc as this is not obvious for people not familiar with multiple S3 file systems story.

yes it worked with s3a:... link, there are other errors, I will try to fix them, thanks a lot

**Comment by zsxwing** [comment]
FYI I submitted #179 to improve the doc
