### ISSUE TITLE
Add OpenAPI documentation(Swagger/Redoc readable) for delta sharing protocol

### ISSUE THREAD

**Issue by amsteel** [delta-io/delta-sharing#297]
.md is good but an Open API spec is much better.
There is one with [riverbank](https://github.com/delta-incubator/riverbank/blob/main/api-description.yml)

**Comment by linzhou-db** [comment]
@amsteel Thanks for the suggestion. 
Do you want to send out a PR for it?

**Comment by linzhou-db** [comment]
closing this issue as the PR is merged.
