### ISSUE TITLE
Documentation of the timestamp format does not match with the actual behavior

### ISSUE THREAD

**Issue by LazyRen** [delta-io/delta-sharing#336]
According to the [protocol's timestamp format documentation](https://github.com/delta-io/delta-sharing/blob/main/PROTOCOL.md#timestamp-format)

1.
> Accepted timestamp format by a delta sharing server: yyyy-[m]m-[d]d hh:mm:ss[.f...].

But the actual delta sharing server only accepts format of `yyyy-MM-dd’T’HH:mm:ss.SSS’Z’`.

2.
> The server will use its local time zone to parse the provided timestamp.

But it actually parses timestamp as of UTC+0 and convert it to the local time zone. I expected DS server to parse timestamp as of local time zone according to the documentation.
I do find the current behavior better, but it would be great if the documentation gets updated to clarify the behavior.

**Comment by linzhou-db** [comment]
@LazyRen Thanks for checking! Created https://github.com/delta-io/delta-sharing/pull/340

**Comment by linzhou-db** [comment]
Closing the issue as the change is made.
