### ISSUE TITLE
Delta Sharing client needs to refresh urls for the correct table version

### ISSUE THREAD

**Issue by charlenelyu-db** [delta-io/delta-sharing#383]
# Issue

Delta sharing spark connector could support long running (> 45 minutes) queries by making an additional RPC with the same parameters, to avoid the expiration of pre-signed urls. Though the refresh may fail under the following conditions:
- The spark query runs longer than the minimum url expiration; **AND**
- The query RPC is a [QueryTable RPC](https://github.com/delta-io/delta-sharing/blob/main/PROTOCOL.md#read-data-from-a-table) on the latest snapshot (`version`/`timestamp` is not specified); **AND**
- Between the initial RPC and the refresh RPC, there are new table versions which made deletion/updates to the table, causing some original files not returned in the refresh RPC.

# Solution

For table shared with history, this issue may be fixed by making the refresh RPC to query the previous version. But for table that are not shared with history, we need a mechanism to allow the refresh RPC to query a historical version and return the same set of files as the initial RPC.

We could introduce a refresh token to the `QueryTable` request. The refresh token will be returned from the initial RPC if requested, and the refresh RPC could specify the refresh token to retrieve the same set of files with refreshed urls. The protocol changes are as follow:

<table>
<tr>
<th>HTTP Request</th>
<th>Value</th>
</tr>
<tr>
<td>Method</td>
<td>

`POST`

</td>
</tr>
<tr>
<td>Headers</td>
<td>

`Authorization: Bearer {token}`
`Content-Type: application/json; charset=utf-8`

</td>
</tr>
<tr>
<td>URL</td>
<td>

`{prefix}/shares/{share}/schemas/{schema}/tables/{table}/query`

</td>
</tr>
<tr>
<td>URL Parameters</td>
<td>

No Change

</td>
</tr>
<tr>
<td>Body</td>
<td>

Add two optional fields:
- **includeRefreshToken** (type: Boolean, optional): whether or not to return a refresh token in the response. This should be set to `true` only when querying the latest snapshot (`version`/`timestamp` is not specified).
-  **refreshToken** (type: String, optional): specifies the refresh token to use to retrieve the same set of files with refreshed urls.

</td>
</tr>
</table>

Example:

`POST {prefix}/shares/vaccine_share/schemas/acme_vaccine_data/tables/vaccine_patients/query`

```json
{
  "includeRefreshToken": true,
  "refreshToken": "..."
}
```

<details>
<summary><b>200: The tables were successfully returned.</b></summary>

<table>
<tr>
<th>HTTP Response</th>
<th>Value</th>
</tr>
<tr>
<td>Headers</td>
<td>

`Content-Type: application/x-ndjson; charset=utf-8`
`Delta-Table-Version: {version}`

</td>
</tr>
<tr>
<td>Body (example)</td>
<td>

```json
{
  "protocol": {
    "minReaderVersion": 1
  }
}
{
  "metaData": {
    "id": "string",
    "format": {
      "provider": "parquet"
    },
    "schemaString": "string",
    "partitionColumns": [
      "date"
    ]
  }
}
{
  "file": {
    "url": "string",
    "id": "string",
    "partitionValues": {
      "date": "2021-04-28"
    },
    "size":573,
    "stats": "string"
  }
}
{
  "endStreamAction": {
    "refreshToken": "string"
  }
}
```

Note: the `endStreamAction` JSON wrapper object must be returned as the last line in the response.

</td>
</tr>
</table>
</details>

**Comment by linzhou-db** [comment]
This is supported in delta-sharing-spark 1.0 now
