### ISSUE TITLE
Unable to run the docker image on both docker desktop and also on kubernetes

### ISSUE THREAD

**Issue by sandeepanumula92** [delta-io/delta-sharing#397]
We are constantly getting File Not Found Exception(No such file of directory) while mounting the server-config.yaml and core-site.xml
The same issue while trying from kubernetes(AKS) - created configmap with server-config.yaml and core-site.xml and mounted this to pod.

Docker tags : 0.6.3 & 0.6.7

Is something wrong with these tags?

**Comment by linzhou-db** [comment]
@sandeepanumula92 Was this resolved?

Are you trying to start your own oss server? 
And why are you using a old tag from 0.6.x? 

For the "File Not Found Exception", what file is it complaining about?

**Comment by linzhou-db** [comment]
cc @zsxwing

**Comment by sandeepanumula92** [comment]
The issue has been fixed after adding **defaultmode : 438** in kubernetes yaml file for volume mounts.
Our nodes are of AMD64 CPU arch - hence the latest image which supports this arch is 0.6.7 & 0.6.3 - so trying with these versions only.
We can't provision new nodepool with ARM64 type because owe enabled defender for cloud and Azure doesn't support adding ARM64 nodepool to AKS if it is enabled.
