### ISSUE TITLE
Add possibility to set endpoint-url for s3

### ISSUE THREAD

**Issue by alarex** [delta-io/delta-sharing#42]
Unfortunately, default AWS variables doesn't support endpoint url for compatible s3 storages, only through CLI "--endpoint-url".  Any chances it could be implemented?

**Comment by zsxwing** [comment]
@alarex do you mean [MinIO](https://min.io/)? Does it support [S3 pre-signed urls](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html)? This is a requirement to use Delta Sharing Server.

**Comment by alarex** [comment]
@zsxwing 
Not exactly minio, but yes, something like that. And presigned urls are supported.

**Comment by zsxwing** [comment]
Makes sense. Do you know how to set this in S3AFileSystem? Feel free to submit a PR if you know how to support this.

**Comment by andrey-puzyr** [comment]
[S3AFileSystem](https://hadoop.apache.org/docs/current/hadoop-aws/tools/hadoop-aws/index.html) supports this using `fs.s3a.endpoint` configuration property.
Does delta-sharing support configuration params? For spark, we use command line conf option, like `spark-submit --conf "spark.hadoop.fs.s3a.endpoint=xyz" ...`. I'm not experienced in scala/java stack, do you have advice how to best setup it?

**Comment by andrey-puzyr** [comment]
I have found a way to override [hadoop conf](https://github.com/delta-io/delta-sharing/blob/main/server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala#L70-L72) in source code
```
  private val conf = withClassLoader {
    val conf = new Configuration()
    conf.set("fs.s3a.endpoint", "https://s3.yandexcloud.net")
    conf
  }
```
Looks like delta-sharing should support aws config overriding out-of-the-box. What the best way to implement it in the future? Can we pass hadoop configuration xml filepath in `delta-sharing-server.yaml`?

**Comment by zsxwing** [comment]
Hadoop configuration xml will be loaded from the classpath. For example, you can create the following `core-site.xml` file

```
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
<configuration>
  <property>
    <name>fs.s3a.endpoint</name>
    <value>https://s3.yandexcloud.net</value>
  </property>
</configuration>
```
and put it in a directory, such as `/foo/bar`.  Then you can add this directory path to the following line in the `bin/delta-sharing-server` file, such as:

```
declare -r app_classpath="/foo/bar:<other existing paths>"
```

This is not convenient. I opened #45 to add the `conf/` directory to the classpath. After this change, you can just put your hadoop configuration file to the `conf/` directory.

**Comment by krisgeus** [comment]
@zsxwing Tested this out in my local setup using localstack as S3 server. Works like a charm. 

I have used this setup in my dcker-compose to run a local docker container with delta-sharing. The docker container is build from this repo with `build/sbt docker:publishLocal`

```
  delta:
    image: delta-sharing-server:0.2.0-SNAPSHOT
    command: ["--config", "/opt/docker/conf/delta-sharing.yml"]
    ports:
      - 38080:8080
    volumes:
      - ./config/:/opt/docker/conf/
```

In my local config directory I have the delta-sharing.yml and a core-site.xml for the hadoop/S3 config

**Comment by krisgeus** [comment]
Would be great to get a 0.2.0 release out with these improvements.

**Comment by zsxwing** [comment]
We have supported this in #45
