### ISSUE TITLE
Can a new release be published

### ISSUE THREAD

**Issue by krisgeus** [delta-io/delta-sharing#47]
While trying out delta-sharing:1.0.0 I ran into some bugs which are resolved by a few merged PR's in main. 

The most important (to me) are:
- Able to add hadoop core-site.xml config to the delta sharing server #42 
- Fix load_as_pandas on table without stats #30 
- Use docker image from sbt docker:publishLocal

would be lovely to have a new release (1.1.0 or 2.0.0??) ( for the python/scala packages at least. A docker image on docker hub would be even more awesome

**Comment by zsxwing** [comment]
Yep. We will do a new release 0.2.0.

**Comment by zsxwing** [comment]
Closing this as 0.2.0 is out.
