### ISSUE TITLE
Python client should handle the "nextPageToken" = "" (empty string) case as described in the document

### ISSUE THREAD

**Issue by tribuipi** [delta-io/delta-sharing#526]
I'm implementing a Delta Sharing server which returns an empty string for "nextPageToken" when there are no additional results as described in the document here: https://github.com/delta-io/delta-sharing/blob/main/PROTOCOL.md#list-shares

```
Note: the nextPageToken field may be an empty string or missing when there are no additional results. The client must handle both cases.
```

But the Python client only works with "None" (missing) case, not the empty string case:
https://github.com/delta-io/delta-sharing/blob/main/python/delta_sharing/delta_sharing.py#L277

With this issue, the Python client will loop forever.

**Comment by pranavsuku-db** [comment]
This has been fixed in the most recent PR and will be released sometime soon
