### ISSUE TITLE
Doc on how to create a "share"?

### ISSUE THREAD

**Issue by felixsafegraph** [delta-io/delta-sharing#60]
If I'm self hosting the server, getting it to read S3, how do I create a share? I've checked https://github.com/delta-io/delta-sharing/blob/main/PROTOCOL.md - which focuses on list share, query table etc.

**Comment by felixsafegraph** [comment]
ok it seems to be in https://github.com/delta-io/delta-sharing/blob/main/server/src/universal/conf/delta-sharing-server.yaml.template

how do we update this? it has to be hand modified and restart the server?

**Comment by zsxwing** [comment]
Yep. Currently, it's a static file. There is a feature request #44 to make it dynamically.

**Comment by felixsafegraph** [comment]
ok, it might help if you could change the title here and add a few words on this https://github.com/delta-io/delta-sharing#config-the-shared-tables-for-the-server

**Comment by felixsafegraph** [comment]
like

## Server configuration and adding Shared Data

- Unpack the pre-built package and copy the server config template file `conf/delta-sharing-server.yaml.template` to create your own server yaml file, such as `conf/delta-sharing-server.yaml`.
- Make changes to your yaml file. You may also need to update some server configs for special requirements.
- To add Shared Data, add reference to  Delta Lake tables you would like to share from this server in this config file.

**Comment by zsxwing** [comment]
👍 Feel free to open a PR to update README 😄

**Comment by felixsafegraph** [comment]
https://github.com/delta-io/delta-sharing/pull/61 done.
