### ISSUE TITLE
Add a new API to Delta Sharing Protocol to list all tables in a share

### ISSUE THREAD

**Issue by zhuansunxt** [delta-io/delta-sharing#64]
Listing all the tables inside a Share is a common metadata retrieval operation. Given the current Delta Sharing Protocol, however, a client has to make one ListSchema API and multiple ListTables API calls in order to list all the tables due to the fact that ListTables API has the scope of a single schema. This may introduce higher traffic load to the sharing server as well as usage frictions to the client, especially when there is a high number of schemas inside a share.

**Comment by zhuansunxt** [comment]
API Proposal: 

### List all Tables in a Share

This is the API to list all the tables under all schemas in a share.

HTTP Parameters | Value
-|-
HTTP Method | GET
Header | Authorization: Bearer {token}
URL | {prefix}/shares/{share}/all-tables
URL Parameters | **{share}**: The share name to query. It's case-insensitive.
Query Parameters | **maxResults** (type: Int, optional): The maximum number of results per page that should be returned. If the number of available results is larger than `maxResults`, the response will provide a `nextPageToken` that can be used to get the next page of results in subsequent list requests. The server may return fewer than `maxResults` items even if there are more available. The client should check `nextPageToken` in the response to determine if there are more available.<br><br>**pageToken** (type: String, optional): Specifies a page token to use. Set `pageToken` to the `nextPageToken` returned by a previous list request to get the next page of results. `nextPageToken` will not be returned in a response if there are no more results available.
Response Header | Content-Type: application/json; charset=utf-8
Response Body | <pre>{<br>  "items": [<br>    {<br>      "name": string<br>      "schema": string<br>      "share": string<br>    }<br>  ],<br>  "nextPageToken": string,<br>}</pre> Note: the `items` field may be an empty array or missing when no results are found. The client must handle both cases.

Example:

```
GET {prefix}/shares/vaccine_share/all-tables

{
   "items" : [
      {
         "share" : "vaccine_share",
         "schema" : "acme_vaccine_ingredient_data",
         "name" : "vaccine_ingredients"
      },
      {
         "share" : "vaccine_share",
         "schema" : "acme_vaccine_patient_data",
         "name" : "vaccine_patients"
      }
   ],
   "nextPageToken" : "..."
}
```

**Comment by zsxwing** [comment]
Added by #63
