### ISSUE TITLE
Read ".parquet" format files in S3

### ISSUE THREAD

**Issue by alison199** [delta-io/delta-sharing#68]
Hi,

I have a question about the delta-sharing project. I am using Python

I have some files stored in S3 in '.parquet' format. I want to be able to load the content of these files directly into a pandas dataframe without having to download them

The parquet format files I need to read, look as follows:

b'PAR1\x15\x00\x15\xb0' etc ...

Can the delta-sharing project read files in .parquet format or only in JSON format ? The reason why I'm asking is because in the code I see many "from_json" and "json.loads" methods

In the file "profile-file-path", for the "endpoint" key of the dictionary I'm using the S3 file location of the parquet file. Is that correct or do I need to use another endpoint ?

I've tried calling the "client.list_schemas()" or "client.list_shares()" or "client.list_tables()" to find out the final "table_url" that I need for the "load_as_pandas" method. The problem is that with the parquet S3 file location "endpoint" I get an error because this content fetched is parquet and not json

Thank you very much,

Alison

**Comment by zhuansunxt** [comment]
Hi,

The `endpoint` field in the profile file is not the storage location of the data files but the URL of the sharing server which exposes Delta Sharing REST APIs. To successfully access the data, you'd need a sharing server deployed to control the data sharing. See more at https://github.com/delta-io/delta-sharing#delta-sharing-reference-server.

Delta Sharing only supports sharing data in Delta/Parquet format. The `from_json` methods you see are implementation details on how the client parses profile file in JSON format.
