### ISSUE TITLE
Delta sharing container on AWS ecs getting access denied error even with all s3 permissions there

### ISSUE THREAD

**Issue by gauravbrills** [delta-io/delta-sharing#73]
Delta sharing container on ecs getting access denied error even with all Iam s3 and kms permission there for the bucket on the ecs service .

Error
``` 
io.delta.sharing.server.DeltaInternalException: java.util.concurrent.ExecutionException: java.nio.file.AccessDeniedException:  s3a://foo-lake/foo/foo_fact/_delta_log: getFileStatus on s3a://foo-lake/foo/foo_fact/_delta_log: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: C0DZXXXYNWKQ9CWD; S3 
Extended Request ID: eDvJMbR8UtIRDg8nXD7+0ix04VN8UPsVSEJDIBosFC5u/YJPsnAGpm/hvGdrXteQBpeQNu5DW9Q=), S3 Extended Request ID: eDvJMbR8UtIRDg8nXD7+0ix04VN8UPsVSEJDIBosFC5u/YJPsnAGpm/hvGdrXteQBpeQNu5DW9Q=
--
@timestamp | 1635392335291 
```

Also 

``` 

(s3a://foo-lake/foo/foo_fact/_delta_log/_delta_log/_last_checkpoint is corrupted.
 Will search the checkpoint files directly,java.nio.file.AccessDeniedException: s3a://foo-lake/foo/foo_fact/_delta_log/_last_checkpoint: getFileStatus on 
s3a://wfg1stg-datahub-lake/ovdm/tran_fact/_delta_log/_last_checkpoint: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: C0DM6WHHRX0RR7DG; S3 Extended Request ID: yEdeFmnz49jLTXu+LzqoNZqFy0sK8X3ge0p7Gmp5ia9FVFjWN7/HLLZ5sWatqfi6cDH0ZRGGf9s=), S3 Extended Request ID: yEdeFmnz49jLTXu+LzqoNZqFy0sK8X3ge0p7Gmp5ia9FVFjWN7/HLLZ5sWatqfi6cDH0ZRGGf9s=)
--
 

```

Shouldn't delta-server already use **EC2ContainerCredentialsProviderWrapper** or if there is a way to still configure this

**Comment by zsxwing** [comment]
We are using hadoop-aws, and it doesn't use `EC2ContainerCredentialsProviderWrapper` by default. And we need to config it.

You can create a Hadoop configuration file named `core-site.xml` and add it to the server's conf directory. Then add the following content to the xml file:

```
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
<configuration>
<property>
  <name>fs.s3a.aws.credentials.provider</name>
  <value>com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper</value>
</property>
</configuration>
```

This is only supported by Delta Sharing Server 0.2.0 or above.

**Comment by gauravbrills** [comment]
Thanks @zsxwing  was trying the same , QQ n the container where should be the default location for the hadoop core-site.xml file should it be the **/conf** folder or the **/config** folder where my delta sharing config yaml resides .

**Comment by zsxwing** [comment]
It should be `/conf`. See https://github.com/delta-io/delta-sharing/pull/45

**Comment by zsxwing** [comment]
> the **/config** folder where my delta sharing config yaml resides .

the yaml can be in any folder. The path is a parameter to pass into the server start script. The directory doesn't matter.

**Comment by gauravbrills** [comment]
> > the **/config** folder where my delta sharing config yaml resides .
> 
> the yaml can be in any folder. The path is a parameter to pass into the server start script. The directory doesn't matter.

Great thanks let me try this yes for the yaml was giving a custom path but didn't know where the default location of hadoop conf/home was assumed but now get it .So the one where I had tried similar changes earlier didn't work .

**Comment by zsxwing** [comment]
@gauravbrills sorry, I noticed a minor typo. It should be the `conf/` inside the unpacked Delta Sharing server package. If you are using the Delta Sharing Server docker image, it will be in `/opt/docker/conf`.

**Comment by gauravbrills** [comment]
Thanks @zsxwing  works like a charm now 👍🏼
