### ISSUE TITLE
Error when configuring for azure datalake gen2

### ISSUE THREAD

**Issue by mendezdl** [delta-io/delta-sharing#79]
Hello, I am configuring delta-sharing for connecting with azure deltalake gen2, but when I call the method .../delta-sharing/shares/{share_name}/schemas/{schema_name}/tables/{table_name}/metadata

An error occurs indicating:
java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.azurebfs.SecureAzureBlobFileSystem not found

I'm using delta-sharing docker image deltaio/delta-sharing-server:0.2.0

Also tried copying libraries  such as hadoop-azure-2.10.1.jar and hadoop-azure-3.3.1.jar but under /opt/docker/lib but the error persist

**Comment by zsxwing** [comment]
0.2.0 doesn't support Azure. We are working on releasing 0.3.0. It will be available soon.

**Comment by mendezdl** [comment]
Thansk, I already tested the 0.3.0-SNAPSHOT and works with azure, but still missing something in the Python library where I can't apply the predicate parameter described in the Protocol definition when querying a table
